version: '3.0'

services:
  db:
    image: postgres:14.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: anylistDB
    volumes: 
      - ./postgres:/var/lib/postgresql/data